service: sg

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:CreateTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:ListTables
      Resource: { "Fn::Join": ["",["arn:aws:dynamodb:",{"Ref":"AWS::Region"},":*:*"]] }
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join": ["", ["arn:aws:s3:::", { "Ref": "ServerlessDeploymentBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: { "Fn::Join": ["", ["arn:aws:s3:::", { "Ref": "ServerlessDeploymentBucket" }, "/*" ] ]  }

plugins:
  - serverless-webpack

resources:
  - ${file(resources/s3-bucket.yml)}

custom: # Add custom section and include webpack configuration
#  webpackIncludeModules: true
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false

functions:
  - ${file(resources/function.yml)}
