service: sg

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:CreateTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:ListTables
      Resource: { "Fn::Join": ["",["arn:aws:dynamodb:",{"Ref":"AWS::Region"},":*:*"]] }
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join": ["", ["arn:aws:s3:::", { "Ref": "ServerlessDeploymentBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: { "Fn::Join": ["", ["arn:aws:s3:::", { "Ref": "ServerlessDeploymentBucket" }, "/*" ] ]  }

plugins:
  - serverless-webpack

custom: # Add custom section and include webpack configuration
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false

functions:
  Playground:
    handler: handler.Playground
  SensorLoggerSave:
    handler: handler.SensorLoggerSave
  SensorLogger:
    handler: handler.SensorLogger
    events:
      - http:
          path: /sensor-logger
          method: get
